Add "Validate Helm Chart" step to "helm-chart-build.yml"

diff --git a/.github/workflows/helm-chart-build.yml b/.github/workflows/helm-chart-build.yml
--- a/.github/workflows/helm-chart-build.yml
+++ b/.github/workflows/helm-chart-build.yml
@@ -61,14 +61,20 @@ jobs:
         run: |
           curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
 
-      - name: Validate App Charts
+      - name: Validate Helm Chart
         run: |
-          app=$(echo "${{ matrix.folder }}" | cut -d'/' -f2)
+          chart=${{ matrix.folder }}
+          app=$(echo "$chart" | cut -d'/' -f2)
+          config="apps/$app/charts/st-charts.yaml"
+          if [ ! -f "$config" ]; then
+            echo "::warning :: Validation config $config not found"
+            exit 0
+          fi
           echo "Validating chart for app: $app"
           python3 ./scripts/chart_ctl.py generate "$app"
-          if ! git diff --quiet; then
-            echo "Invalid $app charts: Run './scripts/chart_ctl.py generate $app' and commit the changes."
-            git diff
+          if ! git diff --quiet "$chart"; then
+            echo -e "Invalid chart $chart:\nRun 'python3 ./scripts/chart_ctl.py generate $app' and commit the changes."
+            git diff "$chart"
             exit 1
           fi
 
